import Layout from "@/components/Layout";
import UpdateProfileModal from "@/components/UpdateProfileModal";
import { useUserProfileContext } from "@/context/UserProfileContext";
import { useProfileImageGetter } from "@/hooks";
import Head from "next/head";
import { useState } from "react";
import {
  Button,
  Divider,
  Grid,
  Icon,
  Image,
  Loader,
  Segment,
  Table,
} from "semantic-ui-react";

export default function Home() {
  const [open, setOpen] = useState(false);
  const { userProfile } = useUserProfileContext();
  const [name, surname] = (userProfile?.fullName || "").split(" ");
  const { image, loading, refetchProfileImage } = useProfileImageGetter(
    userProfile?.username
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Segment placeholder>
          <Grid stackable>
            <Grid.Row centered>
              {loading ? (
                <Loader active size="huge" inline />
              ) : (
                <Image src={image} size="medium" centered />
              )}
            </Grid.Row>
            <Divider inverted />
            <Grid.Row>
              <Table
                definition
                padded
                style={{
                  marginLeft: "auto",
                  marginRight: "auto",
                  width: "30%",
                }}
              >
                <Table.Body>
                  <Table.Row>
                    <Table.Cell width={2}>Name</Table.Cell>
                    <Table.Cell>{name}</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>Surname</Table.Cell>
                    <Table.Cell>{surname}</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>Username</Table.Cell>
                    <Table.Cell>{userProfile?.username}</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>Status</Table.Cell>
                    <Table.Cell>{userProfile?.status}</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>Type</Table.Cell>
                    <Table.Cell>{userProfile?.type}</Table.Cell>
                  </Table.Row>
                </Table.Body>
                <Table.Footer fullWidth>
                  <Table.Row>
                    <Table.HeaderCell colSpan="4">
                      <Button
                        icon
                        labelPosition="left"
                        primary
                        size="small"
                        onClick={() => setOpen(true)}
                      >
                        <Icon name="user" /> Update profile
                      </Button>
                    </Table.HeaderCell>
                  </Table.Row>
                </Table.Footer>
              </Table>
            </Grid.Row>
          </Grid>
        </Segment>
        <UpdateProfileModal
          open={open}
          setOpen={setOpen}
          refetchProfileImage={refetchProfileImage}
        />
      </Layout>
    </>
  );
}
