# Generated by Django 4.2 on 2023-10-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('dean', 'Dean'), ('hod', 'Head of department'), ('prof', 'Professor'), ('assistant', 'Assistant')], default='assistant', max_length=10),
        ),
    ]
