# Generated by Django 4.2 on 2023-10-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_pics/elyse.png', null=True, upload_to='profile_pics/'),
        ),
    ]
